hub:
  cookieSecret: 98a089a34637d725efa49d780b2d324428211a81a51a30913985793507f086d8
  # db:
  #   type: postgres
  #   url: postgres+psycopg2://mphhubadmin@mphhubdbs1:Simple123!@mphhubdbs1.postgres.database.azure.com:5432/hhs_hub
  #   upgrade: true
  extraEnv:
    AAD_TENANT_ID: "56b3f762-b01e-4e87-be31-e4feb4fade9d"
  image:
    pullPolicy: 'Always'
  nodeSelector:
    dedicate.pool: apppool
  extraConfig:
    jupyterlab: |
      c.JupyterHub.authenticator_class = 'jupyterhub.auth.DummyAuthenticator'
      c.KubeSpawner.start_timeout = 3600
    admin_user: |
      c.JupyterHub.admin_access = True
      c.Authenticator.admin_users = {'apiuser','ziang'}
      c.JupyterHub.api_tokens = {'97bbf5d910d0c6d06be880441633953445f6965a78d25b54694f5e26374ffc6a': 'apiuser'}
    spawner: |
      c.KubeSpawner.profile_list = [
        {
          'display_name':'Evolution X',
          'description': 'Linux Desktop. Include Jupyter, RStudio, VSCode, pgAdmin4, Apache Spark, Kubeflow. 2 CPUs, 8GB RAM', 
          'default': False,
          'kubespawner_override': {
            'image': 'pitcrewacr.azurecr.io/novnc-notebook:latest',
            'cmd': ['startup'],
            'image_pull_policy': 'IfNotPresent',
            'cpu_limit': 2,
            'cpu_guarantee': 0.5,
            'mem_limit': '8G',
            'mem_guarantee': '2G',
            'node_selector': {'dedicate.pool': 'jhubuserpool'},
            'volumes': [
              {'name': 'project-claim','persistentVolumeClaim': {'claimName': 'pvc-test-jhub-project'}},
              {'name': 'user-claim','persistentVolumeClaim': {'claimName': 'pvc-test-jhub-user'}},
              {'name': 'job-claim','persistentVolumeClaim': {'claimName': 'pvc-nga-demo-pipeline-jhub'}},
            ],
            'volume_mounts': [
              {'name': 'project-claim','mountPath': '/home/jovyan/Desktop/shared'},
              {'name': 'user-claim','mountPath': '/home/jovyan/Desktop/work'},
              {'name': 'job-claim','mountPath': '/home/jovyan/Desktop/pipeline-run'}
            ],
            'singleuser_extra_pod_config': {
              'service_account_name': 'spark-admin',
              'automount_service_account_token': True,
              'hostAliases': [{'ip': '127.0.0.1', 'hostnames':['jupyter.ds.nga.container','rstudio.ds.nga.container','vscode.appdev.nga.container','pgadmin4.de.nga.container','spark.ds.nga.container']}]
            },
            'extra_containers': [
              {
                'name': 'jupyterlab',
                'image': 'pitcrewacr.azurecr.io/datascience-notebook:latest',
                'command': ['start-notebook.sh'],
                'image_pull_policy': 'IfNotPresent',
                'volume_mounts': [
                  {'name': 'project-claim','mountPath': '/home/jovyan/shared'},
                  {'name': 'user-claim','mountPath': '/home/jovyan/work'},
                  {'name': 'job-claim','mountPath': '/home/jovyan/pipeline-run'}
                ],
              },
              {
                'name': 'rstudio',
                'image': 'pitcrewacr.azurecr.io/rstudio:latest',
                'image_pull_policy': 'IfNotPresent',
                'volume_mounts': [
                  {'name': 'project-claim','mountPath': '/home/jovyan/shared'},
                  {'name': 'user-claim','mountPath': '/home/jovyan/work'},
                  {'name': 'job-claim','mountPath': '/home/jovyan/pipeline-run'}
                ],
              },
              {
                'name': 'spark',
                'image': 'pitcrewacr.azurecr.io/pyspark-notebook:v2.4.5',
                'command': ['start-notebook.sh'],
                'image_pull_policy': 'IfNotPresent',
                'volume_mounts': [
                  {'name': 'project-claim','mountPath': '/home/jovyan/shared'},
                  {'name': 'user-claim','mountPath': '/home/jovyan/work'},
                  {'name': 'job-claim','mountPath': '/home/jovyan/pipeline-run'}
                ],
                'env': [
                  {'name': 'MY_POD_IP', 'valueFrom': { 'fieldRef' : { 'fieldPath' : 'status.podIP' } } }
                ],
              },
              {
                'name': 'theia-vscode',
                'image': 'pitcrewacr.azurecr.io/theia-vscode:latest',
                'image_pull_policy': 'IfNotPresent',
                'volume_mounts': [
                  {'name': 'project-claim','mountPath': '/home/jovyan/shared'},
                  {'name': 'user-claim','mountPath': '/home/jovyan/work'},
                  {'name': 'job-claim','mountPath': '/home/jovyan/pipeline-run'}
                ],
              },
              {
                'name': 'pgadmin4',
                'image': 'pitcrewacr.azurecr.io/pgadmin4:latest',
                'image_pull_policy': 'IfNotPresent',
                'command': ['/entrypoint.sh'],
                'env': [{'name':'PGADMIN_DEFAULT_EMAIL', 'value':'admin@pgadmin4.dii.hhs.info'}, 
                        {'name':'PGADMIN_DEFAULT_PASSWORD', 'value':'admin'}, 
                        {'name':'PGADMIN_LISTEN_PORT', 'value':'5050'},
                        {'name':'PGADMIN_CONFIG_SERVER_MODE','value':'False'}]
              },
            ]
          }
        },
        {
          'display_name':'Evolution GT',
          'description': 'Linux Desktop. Include Tensorflow, RStudio, Apache Spark, Kubeflow. 4 CPUs, 32GB RAM, NVIDIA Tesla K80 12GB', 
          'default': False,
          'kubespawner_override': {
            'image': 'pitcrewacr.azurecr.io/novnc-notebook:latest',
            'cmd': ['startup'],
            'image_pull_policy': 'IfNotPresent',
            'cpu_limit': 4,
            'cpu_guarantee': 2,
            'mem_limit': '32G',
            'mem_guarantee': '8G',
            'node_selector': {'dedicate.pool': 'gpupool'},
            'extra_resource_guarantees' : {"nvidia.com/gpu": 1},
            'extra_resource_limits' : {"nvidia.com/gpu": 1},
            'volumes': [
              {'name': 'project-claim','persistentVolumeClaim': {'claimName': 'pvc-test-jhub-project'}},
              {'name': 'user-claim','persistentVolumeClaim': {'claimName': 'pvc-test-jhub-user'}},
              {'name': 'job-claim','persistentVolumeClaim': {'claimName': 'pvc-nga-demo-pipeline-jhub'}},
            ],
            'volume_mounts': [
              {'name': 'project-claim','mountPath': '/home/jovyan/Desktop/shared'},
              {'name': 'user-claim','mountPath': '/home/jovyan/Desktop/work'},
              {'name': 'job-claim','mountPath': '/home/jovyan/Desktop/pipeline-run'}
            ],
            'singleuser_extra_pod_config': {
              'service_account_name': 'spark-admin',
              'automount_service_account_token': True,
              'hostAliases': [{'ip': '127.0.0.1', 'hostnames':['jupyter.ds.nga.container','rstudio.ds.nga.container','vscode.appdev.nga.container','pgadmin4.de.nga.container','spark.ds.nga.container']}]
            },
            'extra_containers': [
              {
                'name': 'jupyterlab',
                'image': 'pitcrewacr.azurecr.io/tensorflow-notebook:2.4.1',
                'command': ['start-notebook.sh'],
                'image_pull_policy': 'IfNotPresent',
                'volume_mounts': [
                  {'name': 'project-claim','mountPath': '/home/jovyan/shared'},
                  {'name': 'user-claim','mountPath': '/home/jovyan/work'},
                  {'name': 'job-claim','mountPath': '/home/jovyan/pipeline-run'}
                ],
              },
              {
                'name': 'rstudio',
                'image': 'pitcrewacr.azurecr.io/rstudio:latest',
                'image_pull_policy': 'IfNotPresent',
                'volume_mounts': [
                  {'name': 'project-claim','mountPath': '/home/jovyan/shared'},
                  {'name': 'user-claim','mountPath': '/home/jovyan/work'},
                  {'name': 'job-claim','mountPath': '/home/jovyan/pipeline-run'}
                ],
              },
              {
                'name': 'spark',
                'image': 'pitcrewacr.azurecr.io/pyspark-notebook:v2.4.5',
                'command': ['start-notebook.sh'],
                'image_pull_policy': 'IfNotPresent',
                'volume_mounts': [
                  {'name': 'project-claim','mountPath': '/home/jovyan/shared'},
                  {'name': 'user-claim','mountPath': '/home/jovyan/work'},
                  {'name': 'job-claim','mountPath': '/home/jovyan/pipeline-run'}
                ],
                'env': [
                  {'name': 'MY_POD_IP', 'valueFrom': { 'fieldRef' : { 'fieldPath' : 'status.podIP' } } }
                ]
              },
              {
                'name': 'theia-vscode',
                'image': 'pitcrewacr.azurecr.io/theia-vscode:latest',
                'image_pull_policy': 'IfNotPresent',
                'volume_mounts': [
                  {'name': 'project-claim','mountPath': '/home/jovyan/shared'},
                  {'name': 'user-claim','mountPath': '/home/jovyan/work'},
                  {'name': 'job-claim','mountPath': '/home/jovyan/pipeline-run'}
                ],
              },
              {
                'name': 'pgadmin4',
                'image': 'pitcrewacr.azurecr.io/pgadmin4:latest',
                'image_pull_policy': 'IfNotPresent',
                'command': ['/entrypoint.sh'],
                'env': [{'name':'PGADMIN_DEFAULT_EMAIL', 'value':'admin@pgadmin4.dii.hhs.info'}, 
                        {'name':'PGADMIN_DEFAULT_PASSWORD', 'value':'admin'}, 
                        {'name':'PGADMIN_LISTEN_PORT', 'value':'5050'},
                        {'name':'PGADMIN_CONFIG_SERVER_MODE','value':'False'}]
              },
            ]
          }
        },
        {
          'display_name':'Mustang Geo',
          'description': 'Linux Desktop. Include Sklearn, GeoPandas, OSMNX, ArcGIS SDK, PostgresGIS, Kubeflow. 2 CPUs, 8GB RAM', 
          'default': True,
          'kubespawner_override': {
            'image': 'pitcrewacr.azurecr.io/novnc-notebook:latest',
            'cmd': ['startup'],
            'image_pull_policy': 'IfNotPresent',
            'cpu_limit': 2,
            'cpu_guarantee': 0.5,
            'mem_limit': '8G',
            'mem_guarantee': '2G',
            'node_selector': {'dedicate.pool': 'jhubuserpool'},
            'volumes': [
              {'name': 'project-claim','persistentVolumeClaim': {'claimName': 'pvc-test-jhub-project'}},
              {'name': 'user-claim','persistentVolumeClaim': {'claimName': 'pvc-test-jhub-user'}},
              {'name': 'job-claim','persistentVolumeClaim': {'claimName': 'pvc-nga-demo-pipeline-jhub'}},
            ],
            'volume_mounts': [
              {'name': 'project-claim','mountPath': '/home/jovyan/Desktop/shared'},
              {'name': 'user-claim','mountPath': '/home/jovyan/Desktop/work'},
              {'name': 'job-claim','mountPath': '/home/jovyan/Desktop/pipeline-run'}
            ],
            'singleuser_extra_pod_config': {
              'service_account_name': 'spark-admin',
              'automount_service_account_token': True,
              'hostAliases': [{'ip': '127.0.0.1', 'hostnames':['jupyter.ds.nga.container','rstudio.ds.nga.container','vscode.appdev.nga.container','pgadmin4.de.nga.container','spark.ds.nga.container']}]
            },
            'extra_containers': [
              {
                'name': 'jupyterlab',
                'image': 'pitcrewacr.azurecr.io/gis-notebook:latest',
                'command': ['start-notebook.sh'],
                'image_pull_policy': 'IfNotPresent',
                'volume_mounts': [
                  {'name': 'project-claim','mountPath': '/home/jovyan/shared'},
                  {'name': 'user-claim','mountPath': '/home/jovyan/work'},
                  {'name': 'job-claim','mountPath': '/home/jovyan/pipeline-run'}
                ],
              },
              {
                'name': 'rstudio',
                'image': 'pitcrewacr.azurecr.io/rstudio:latest',
                'image_pull_policy': 'IfNotPresent',
                'volume_mounts': [
                  {'name': 'project-claim','mountPath': '/home/jovyan/shared'},
                  {'name': 'user-claim','mountPath': '/home/jovyan/work'},
                  {'name': 'job-claim','mountPath': '/home/jovyan/pipeline-run'}
                ],
              },
              {
                'name': 'spark',
                'image': 'pitcrewacr.azurecr.io/pyspark-notebook:v2.4.5',
                'command': ['start-notebook.sh'],
                'image_pull_policy': 'IfNotPresent',
                'volume_mounts': [
                  {'name': 'project-claim','mountPath': '/home/jovyan/shared'},
                  {'name': 'user-claim','mountPath': '/home/jovyan/work'},
                  {'name': 'job-claim','mountPath': '/home/jovyan/pipeline-run'}
                ],
                'env': [
                  {'name': 'MY_POD_IP', 'valueFrom': { 'fieldRef' : { 'fieldPath' : 'status.podIP' } } }
                ]
              },
              {
                'name': 'theia-vscode',
                'image': 'pitcrewacr.azurecr.io/theia-vscode:latest',
                'image_pull_policy': 'IfNotPresent',
                'volume_mounts': [
                  {'name': 'project-claim','mountPath': '/home/jovyan/shared'},
                  {'name': 'user-claim','mountPath': '/home/jovyan/work'},
                  {'name': 'job-claim','mountPath': '/home/jovyan/pipeline-run'}
                ],
              },
              {
                'name': 'pgadmin4',
                'image': 'pitcrewacr.azurecr.io/pgadmin4:latest',
                'image_pull_policy': 'IfNotPresent',
                'command': ['/entrypoint.sh'],
                'env': [{'name':'PGADMIN_DEFAULT_EMAIL', 'value':'admin@pgadmin4.dii.hhs.info'}, 
                        {'name':'PGADMIN_DEFAULT_PASSWORD', 'value':'admin'}, 
                        {'name':'PGADMIN_LISTEN_PORT', 'value':'5050'},
                        {'name':'PGADMIN_CONFIG_SERVER_MODE','value':'False'}]
              },
            ]
          }
        }
      ]

cull:
  enabled: true
  timeout: 3600
  every: 600
  
scheduling:
  userScheduler:
    enabled: true
    nodeSelector:
      dedicate.pool: apppool
  podPriority:
    enabled: true
  userPlaceholder:
    replicas: 0
  userPods:
    nodeAffinity:
      matchNodePurpose: require

# prePuller:
#   extraTolerations:
#   - key: "hub.jupyter.org/dedicated"
#     operator: "Equal"
#     value: "user"
#     effect: "NoSchedule"
#   hook:
#     enabled: true
#     nodeSelector:
#       dedicate.pool: apppool
#   continuous:
#     enabled: true

      
proxy:
  traefik:
    nodeSelector:
      dedicate.pool: apppool
  chp:
    nodeSelector:
      dedicate.pool: apppool
  secretToken: 98a089a34637d725efa49d780b2d324428211a81a51a30913985793507f086d9
  https:
    enabled: false