###### Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nga-demo-pipeline
  labels:
    usage: pv-nga-demo-pipeline
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-fileshare-secret
    shareName: sc-kubeflow-storage
    readOnly: false
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nga-demo-pipeline-jhub
  labels:
    usage: pv-nga-demo-pipeline-jhub
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-fileshare-secret
    shareName: sc-kubeflow-storage
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nga-demo-pipeline
  namespace: kubeflow-user-example-com
  # Set this annotation to NOT let Kubernetes automatically create
  # a persistent volume for this volume claim.
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    # To make sure we match the claim with the exact volume, match the label
    matchLabels:
      usage: pv-nga-demo-pipeline
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nga-demo-pipeline-jhub
  namespace: pitcrew-jhub
  # Set this annotation to NOT let Kubernetes automatically create
  # a persistent volume for this volume claim.
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  selector:
    # To make sure we match the claim with the exact volume, match the label
    matchLabels:
      usage: pv-nga-demo-pipeline-jhub